// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckysolqtpnvjvxegczqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXNvbHF0cG52anZ4ZWdjenF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTI3OTUsImV4cCI6MjA3NDIyODc5NX0.gY5LcW_wJxsqoufcO97_Bnu86smfggP7Vpm7EqJcmaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});